Build website
torobucci/GlobalGroove-Concert pull request #1
Opened 2023-02-13 13:08 UTC by torobucci

2023-02-15 15:53 UTC, ShadyShawkat requested changes
## Hi @torobucci, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- All linters are passing ✔️ 
- Correct use of GitHub Flow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-15 15:53 UTC, ShadyShawkat commented on about.html
> +            </div>
- [ ] It would be better to wrap this section in a `ul` instead of a `div` as this section represents a list of items that are related to each other. You can use something like the following:

```javascript
<ul>
   <li>
      <i>...
      ...
   </li>
   <li>
      <i>...
      ...
   </li>
   ...
</ul>
```

2023-02-15 15:53 UTC, ShadyShawkat commented on about.html
> +                </div>
- [ ] Kindly make sure that on mobile view, the images are bigger and the text on them is visible to match the given design.
- [ ] Please make sure that the text on each image are actual text in the HTML instead of having it as a part of the image so it's easier to change and adjust later on.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/219072226-f32da699-ca3e-449e-a977-0e999dbd93ff.png) | ![image](https://user-images.githubusercontent.com/62290545/219072745-17b97da2-75f3-43c5-9458-10770b5862f3.png) |

2023-02-15 15:53 UTC, ShadyShawkat commented on about.html
> +                </div>
- [ ] Please center the images in this section to be in the center of the screen on the desktop view to match the given design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/219077489-5dbf32c9-494b-40a7-889b-cdd4206cc469.png) | ![image](https://user-images.githubusercontent.com/62290545/219078204-9e25e7c5-4822-4625-b614-34c5f816d26a.png) |

- [HINT] You can see from the following image that the div itself is centered but the images contained within it are overflowing outside it which gives the look of uncentered images. This happens here because you gave each image `width: 60%`.
![image](https://user-images.githubusercontent.com/62290545/219078978-596e4c8e-271c-4dde-a869-6f7818e4342d.png)

2023-02-16 14:56 UTC, gemmen29 approved these changes
Hi @torobucci, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 07:21 UTC, merged